### ISSUE TITLE
Error icon is cropped on small screen

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/text-field#10]
## Component
- [ ] In error state when the screen size is smaller than 320px the icon is cropped, check http://localhost:8080/?path=/story/textfieldlabel--react-theme-all-states as reference
![image](https://user-images.githubusercontent.com/10554673/77870743-2eceba80-727d-11ea-9d26-8127ee5e7fcc.png)

**Comment by Kosukeee** [comment]
Fixed the issue,
https://github.com/rakuten-rex/text-field/commit/00ab6ede806fe0a80adf5385a44c129d8a2de4de

**Comment by claudio-moya** [comment]
thanx!
