### ISSUE TITLE
Theme for icons is not working

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/text-field#11]
## Theme
- [ ] Icon for Error and Valid states are not working in the following stories:
http://localhost:8080/?path=/story/textfieldlabel--react-theme-all-states
http://localhost:8080/?path=/story/textfieldui--react-theme-all-states

![image](https://user-images.githubusercontent.com/10554673/77871353-d13b6d80-727e-11ea-998b-bede6787e13e.png)

**Comment by Kosukeee** [comment]
Separated icon theme,
https://github.com/rakuten-rex/text-field/commit/9aa290d2dc15fe4f807e8547df579d189d0cb964

**Comment by claudio-moya** [comment]
thanx!
