### ISSUE TITLE
BrowserStack QA

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/text-field#4]
## Text Field
- [x] Default Label
https://rakuten-rex.github.io/text-field/iframe.html?id=textfieldlabel--default-view
- [x] Active
https://rakuten-rex.github.io/text-field/iframe.html?id=textfieldlabel--focus-and-active-state
- [x] Theme
https://rakuten-rex.github.io/text-field/iframe.html?id=textfieldlabel--with-theme-react-and-css-vars

**Comment by Kosukeee** [comment]
h1 The issue
---
CSS variables doesn't work on IE11 (components are missing style like border)
(Theme HTML works correctly on IE11)

**Comment by claudio-moya** [comment]
thanx
