### ISSUE TITLE
Theme colors standardization

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/text-field#9]
Default Border Color #CB0085 (Pink 700)
Default Placeholder Text Color  #EF0AA1 (Pink 600)
Default Text Color #A2006A (Pink 800)
Default Label Text Color #CB0085 (Pink 700)
Default Helper Text Color #686868 (Gray 700)

Hover Border Color #A2006A (Pink 800) 
Hover Placeholder Color #CB0085 (Pink 700)
Hover Text Color #830056 (Pink 900)
Hover Label Text Color #A2006A (Pink 800) 
Hover Helper Text Color #4D4D4D (Gray 800)

Active Border Color #830056 (Pink 900)
Active Placeholder Color #A2006A (Pink 800)
Active Text Color #5A003C (Pink 1000)
Active Label Text Color #830056 (Pink 900)
Active Helper Text Color #333333 (Gray 900)

Disabled Border Color #686868 (Gray 700)
Disabled Placeholder Text Color #828282 (Gray 600)
Disabled Text Color #4D4D4D (Gray 800)
Disabled Label Text Color #686868 (Gray 700)
Disabled Helper Text Color #686868 (Gray 700)

Error Border Color #9B00EC (Purple 700)
Error Placeholder Color #B62AFF (Purple 600)
Error Text Color #7D00BE (Purple 800)
Error Label Text Color #9B00EC (Purple 700)
Error Helper Text Color #9B00EC (Purple 700)

Valid Border Color #0085C7 (Light blue 700)
Valid Placeholder Color #00A0F0 (Light blue 600)
Valid Text Color #006A9E (Light blue 800)
Valid Label Text Color #0085C7 (Light blue 700)
Valid Helper Text Color #0085C7 (Light blue 700)

**Comment by Kosukeee** [comment]
Added theme standardization,
https://github.com/rakuten-rex/text-field/commit/6513c0ed8ed8ef9d1f00e7641c877859069eec95

**Comment by claudio-moya** [comment]
thanx
